### ISSUE TITLE
Senior Frontend Software Engineer - Neighborhood

### ISSUE THREAD

**Issue by scps960740** [neighborhood-protocol/neighborhood-hiring#1]
## Senior Frontend Software Engineer - Neighborhood
Hybrid (Full-time Onsite & Remote)

### Responsibility
Neighborhood is a protocol that helps people launch Membership-pass in Web3. Our mission is to leverage the more use cases on the ERC1155 token standard, bridging the whole blockchain communities, no matter whether it is DeFi, NFTs, DAO, or Web3 layers. 

### Our Team
The team in Neighborhood Labs is dedicated to building on Neighborhood protocol. Focus on the DApps(Decentralized Application) usage, and create the outperformance product users will like. We want you to put the user first and exciting about Blockchain tech knowledge.

### Responsibilities
1. Responsible for the frontend development of the Neighborhood DApps.
2. Support us to complete the prototype product and launch it to BSC & ETH Mainnet asap. 

### Requirements
- Minimum 5+ years developing production JavaScript code and strong knowledge of React.
- Experience with modern front-end technologies (styled system, webpack etc).
- Experience with server-side technologies (Next.js, SSR, etc).
- Interesting in Web3.
- Teams collaboration and communicate in English & Chinese.

**Comment by howardpen9** [comment]
Deck Intro
https://docsend.com/view/pc5dkzufvdr9zcje

Password:hood_eth
